language: c
compiler: gcc

addons:
  apt:
    packages:
    - lua5.1
    - liblua5.1-0-dev
    - luarocks

# Tool setup.
install:
  - sudo luarocks install lpeg
  - sudo luarocks install linenoise
  - sudo luarocks install luacheck

# Build and test.
script:
  - make
  - make -C src luacheck
  - make -C src fulltest

branches:
  only:
    - master

