language: c
compiler: gcc

# Tool setup.
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq lua5.1 liblua5.1-0-dev
  - sudo apt-get install -qq luarocks
  - sudo luarocks install lpeg
  - sudo luarocks install linenoise
  - sudo luarocks install luacheck

# Build and test.
script:
  - make
  - make -C src luacheck
  - make -C src fulltest

branches:
  only:
    - master

